# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  secret_key_base: 8de9671ce35c5bf7b79b998196ace9a3d70904b89f71951501779c12b0c4ca0ed70720e237d2be3b9d223369ef70dcaa85663eda8173b1953a460826f2fd5574
  host: 127.0.0.1
  port: 3000
  devise:
    secret_key: 72170c245efb72dc9898c0fd4c5720c459a921df63550c8ebb66ddc3b7f9be17c5f094ec6fa44602e39344327a54203bee6d36cc152228d2835bf2a4f3eecfb0
    mailer_sender: please-change-me-at-secrets@example.com
    pepper: 78cd08fcc22bac757d6697291a64bb264151f90511b230b0551381108765601351dc62cf184c2a5baf10b78c0f504620a882f5bb4d300b29a5c2b37a51c47c76

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
