default: &default
  secret_key_base: 8de9671ce35c5bf7b79b998196ace9a3d70904b89f71951501779c12b0c4ca0ed70720e237d2be3b9d223369ef70dcaa85663eda8173b1953a460826f2fd5574
  host: 127.0.0.1
  port: 3000
  devise:
    secret_key: 72170c245efb72dc9898c0fd4c5720c459a921df63550c8ebb66ddc3b7f9be17c5f094ec6fa44602e39344327a54203bee6d36cc152228d2835bf2a4f3eecfb0
    pepper: 78cd08fcc22bac757d6697291a64bb264151f90511b230b0551381108765601351dc62cf184c2a5baf10b78c0f504620a882f5bb4d300b29a5c2b37a51c47c76
  omniauth:
    facebook:
      key:
      secret:
    twitter:
      key:
      secret:
    google_oauth2:
      key:
      secret:
  mail:
    # config/environments/development.rb & config/environments/production.rb
    # email-smtp.us-east-1.amazonaws.com, smtp.sendgrid.net, ...
    address:
    # 25, 465 or 587
    port:
    username:
    password:
    # sender@example.com
    from: 'sender <sender@example.com>'
    reply_to: 'sender <sender@example.com>'
  stripe:
    # test keys
    secret: sk_test_hw19GOxgMpplcQk9tuhX2IBU
    publishable: pk_test_q69HmiLvkuUqeaUXtX7rNy94

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default